image: node:10.16.3

cache:
  paths:
  - node_modules/

jobs:
  build:
    machine : true
    steps:
      - checkout
      #- run : npm run install
      - run : npm run test
      - run : echo "Test passé"
